/**
 * Sauvegarde SQL complète (schéma + données) du schéma public.
 * Fichier .sql importable dans Postico / psql, y compris sur une base vide.
 */

import { promises as fs } from 'fs'
import path from 'path'
import { Pool, type PoolClient } from 'pg'

export const BACKUP_FORMAT_VERSION = 4
export const BACKUP_FILENAME_RE = /^kpi-banque-\d{8}-\d{6}\.(sql|json\.gz)$/

const DATABASE_URL = process.env.DATABASE_URL ?? 'postgresql://localhost:5432/kpi_banque'
const INSERT_BATCH = 80

export type BackupFileInfo = {
  filename: string
  size: number
  createdAt: string
}

export type BackupCreated = BackupFileInfo & {
  tableCounts: Record<string, number>
}

type ColumnDef = {
  table: string
  name: string
  dataType: string
  notNull: boolean
  defaultExpr: string | null
  identity: string
}

type ConstraintDef = {
  table: string
  name: string
  type: string
  def: string
}

type SchemaDump = {
  enums: { name: string; labels: string[] }[]
  sequences: { name: string; lastValue: string | null }[]
  columns: ColumnDef[]
  constraints: ConstraintDef[]
  indexes: string[]
}

function quoteIdent(name: string): string {
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) {
    throw new Error(`Nom d'identifiant invalide: ${name}`)
  }
  return `"${name.replaceAll('"', '""')}"`
}

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`
}

function sqlLiteral(value: unknown): string {
  if (value === null || value === undefined) return 'NULL'
  if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE'
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'NULL'
  if (typeof value === 'bigint') return value.toString()
  if (value instanceof Date) return `${sqlString(value.toISOString())}::timestamptz`
  if (Buffer.isBuffer(value)) return `E'\\\\x${value.toString('hex')}'`
  if (Array.isArray(value)) {
    if (value.length === 0) return `'{}'`
    return `ARRAY[${value.map(sqlLiteral).join(', ')}]`
  }
  if (typeof value === 'object') return `${sqlString(JSON.stringify(value))}::jsonb`
  return sqlString(String(value))
}

export function getBackupDir(): string {
  return process.env.BACKUP_DIR?.trim() || path.join(process.cwd(), 'data', 'backups')
}

export function getBackupKeep(): number {
  const n = parseInt(process.env.BACKUP_KEEP ?? '10', 10)
  return Number.isFinite(n) && n > 0 ? n : 10
}

export function isSafeBackupFilename(filename: string): boolean {
  return BACKUP_FILENAME_RE.test(filename)
}

function pad2(n: number): string {
  return String(n).padStart(2, '0')
}

export function makeBackupFilename(date = new Date()): string {
  const y = date.getFullYear()
  const m = pad2(date.getMonth() + 1)
  const d = pad2(date.getDate())
  const h = pad2(date.getHours())
  const min = pad2(date.getMinutes())
  const s = pad2(date.getSeconds())
  return `kpi-banque-${y}${m}${d}-${h}${min}${s}.sql`
}

export function resolveBackupPath(filename: string): string {
  if (!isSafeBackupFilename(filename)) {
    throw new Error('Nom de fichier invalide')
  }
  const dir = path.resolve(getBackupDir())
  const resolved = path.resolve(dir, filename)
  if (!resolved.startsWith(dir + path.sep) && resolved !== dir) {
    throw new Error('Nom de fichier invalide')
  }
  return resolved
}

function columnSql(col: ColumnDef): string {
  const parts = [quoteIdent(col.name), col.dataType]
  if (col.identity === 'd') parts.push('GENERATED BY DEFAULT AS IDENTITY')
  else if (col.identity === 'a') parts.push('GENERATED ALWAYS AS IDENTITY')
  else if (col.defaultExpr) parts.push(`DEFAULT ${col.defaultExpr}`)
  if (col.notNull) parts.push('NOT NULL')
  return `  ${parts.join(' ')}`
}

function buildCreateTablesSql(schema: SchemaDump, tableNames: string[]): string {
  const colsByTable = new Map<string, ColumnDef[]>()
  for (const col of schema.columns) {
    const list = colsByTable.get(col.table) ?? []
    list.push(col)
    colsByTable.set(col.table, list)
  }
  const pkeys = schema.constraints.filter((c) => c.type === 'p')

  const chunks: string[] = ['-- Schéma : types, séquences, tables\n']

  if (tableNames.length > 0) {
    chunks.push(`DROP TABLE IF EXISTS ${tableNames.map(quoteIdent).join(', ')} CASCADE;\n`)
  }
  for (const en of schema.enums) {
    chunks.push(`DROP TYPE IF EXISTS ${quoteIdent(en.name)} CASCADE;`)
  }
  if (schema.enums.length > 0) chunks.push('')
  for (const en of schema.enums) {
    const labels = en.labels.map(sqlString).join(', ')
    chunks.push(`CREATE TYPE ${quoteIdent(en.name)} AS ENUM (${labels});`)
  }
  if (schema.enums.length > 0) chunks.push('')

  for (const seq of schema.sequences) {
    chunks.push(`CREATE SEQUENCE IF NOT EXISTS ${quoteIdent(seq.name)};`)
  }
  if (schema.sequences.length > 0) chunks.push('')

  for (const table of tableNames) {
    const cols = colsByTable.get(table) ?? []
    const pk = pkeys.find((c) => c.table === table)
    const body = cols.map(columnSql)
    if (pk) body.push(`  CONSTRAINT ${quoteIdent(pk.name)} ${pk.def}`)
    chunks.push(`CREATE TABLE ${quoteIdent(table)} (\n${body.join(',\n')}\n);\n`)
  }

  const uniquesAndChecks = schema.constraints.filter((c) => c.type === 'u' || c.type === 'c')
  if (uniquesAndChecks.length > 0) {
    chunks.push('-- Contraintes UNIQUE / CHECK')
    for (const c of uniquesAndChecks) {
      chunks.push(
        `ALTER TABLE ${quoteIdent(c.table)} ADD CONSTRAINT ${quoteIdent(c.name)} ${c.def};`
      )
    }
    chunks.push('')
  }

  if (schema.indexes.length > 0) {
    chunks.push('-- Index')
    for (const def of schema.indexes) {
      chunks.push(`${def};`)
    }
    chunks.push('')
  }

  return chunks.join('\n')
}

function buildForeignKeysSql(schema: SchemaDump): string {
  const fks = schema.constraints.filter((c) => c.type === 'f')
  if (fks.length === 0) return ''
  const lines = ['-- Clés étrangères']
  for (const c of fks) {
    lines.push(
      `ALTER TABLE ${quoteIdent(c.table)} ADD CONSTRAINT ${quoteIdent(c.name)} ${c.def};`
    )
  }
  lines.push('')
  return lines.join('\n')
}

function buildInsertSql(table: string, rows: Record<string, unknown>[]): string {
  if (rows.length === 0) return `-- ${table}: 0 ligne\n`
  const columns = Object.keys(rows[0])
  const quotedCols = columns.map(quoteIdent).join(', ')
  const quotedTable = quoteIdent(table)
  const chunks: string[] = [`-- ${table}: ${rows.length} ligne(s)\n`]
  for (let i = 0; i < rows.length; i += INSERT_BATCH) {
    const batch = rows.slice(i, i + INSERT_BATCH)
    const values = batch
      .map((row) => `(${columns.map((col) => sqlLiteral(row[col])).join(', ')})`)
      .join(',\n  ')
    chunks.push(`INSERT INTO ${quotedTable} (${quotedCols}) VALUES\n  ${values};\n`)
  }
  return chunks.join('\n')
}

function buildSqlDump(input: {
  createdAt: string
  schema: SchemaDump
  tables: Record<string, Record<string, unknown>[]>
}): string {
  const tableNames = Object.keys(input.tables)
  const lines: string[] = [
    `-- Sauvegarde KPI Banque`,
    `-- Format v${BACKUP_FORMAT_VERSION} — ${input.createdAt}`,
    `-- Restauration (Postico : Query → coller / exécuter, ou : psql -d NOM_BASE -f ce-fichier.sql)`,
    `-- Inclut CREATE TABLE / ENUM / séquences. ATTENTION : remplace les tables existantes.`,
    ``,
    `BEGIN;`,
    ``,
    buildCreateTablesSql(input.schema, tableNames),
    `SET session_replication_role = replica;`,
    ``,
  ]

  for (const name of tableNames) {
    lines.push(buildInsertSql(name, input.tables[name]))
  }

  lines.push(`SET session_replication_role = DEFAULT;`, ``)
  lines.push(buildForeignKeysSql(input.schema))

  if (input.schema.sequences.length > 0) {
    lines.push(`-- Séquences`)
    for (const seq of input.schema.sequences) {
      if (seq.lastValue == null) continue
      lines.push(
        `SELECT setval(${quoteIdent(seq.name)}::regclass, ${seq.lastValue}, true);`
      )
    }
    lines.push(``)
  }

  lines.push(`COMMIT;`, ``)
  return lines.join('\n')
}

async function fetchSchema(client: PoolClient): Promise<SchemaDump> {
  const enumRows = await client.query<{ typname: string; enumlabel: string }>(
    `SELECT t.typname, e.enumlabel
     FROM pg_catalog.pg_type t
     JOIN pg_catalog.pg_enum e ON e.enumtypid = t.oid
     JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
     WHERE n.nspname = 'public'
     ORDER BY t.typname, e.enumsortorder`
  )
  const enumsMap = new Map<string, string[]>()
  for (const row of enumRows.rows) {
    const labels = enumsMap.get(row.typname) ?? []
    labels.push(row.enumlabel)
    enumsMap.set(row.typname, labels)
  }

  const seqRows = await client.query<{ sequencename: string; last_value: string | null }>(
    `SELECT sequencename, last_value::text AS last_value
     FROM pg_catalog.pg_sequences
     WHERE schemaname = 'public'
     ORDER BY sequencename`
  )

  const colRows = await client.query<{
    table_name: string
    column_name: string
    data_type: string
    not_null: boolean
    default_expr: string | null
    identity: string
  }>(
    `SELECT
       c.relname AS table_name,
       a.attname AS column_name,
       pg_catalog.format_type(a.atttypid, a.atttypmod) AS data_type,
       a.attnotnull AS not_null,
       pg_get_expr(ad.adbin, ad.adrelid) AS default_expr,
       a.attidentity AS identity
     FROM pg_catalog.pg_attribute a
     JOIN pg_catalog.pg_class c ON a.attrelid = c.oid
     JOIN pg_catalog.pg_namespace n ON c.relnamespace = n.oid
     LEFT JOIN pg_catalog.pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
     WHERE n.nspname = 'public'
       AND c.relkind = 'r'
       AND a.attnum > 0
       AND NOT a.attisdropped
     ORDER BY c.relname, a.attnum`
  )

  const constraintRows = await client.query<{
    table_name: string
    conname: string
    contype: string
    def: string
  }>(
    `SELECT
       cl.relname AS table_name,
       co.conname,
       co.contype,
       pg_get_constraintdef(co.oid, true) AS def
     FROM pg_catalog.pg_constraint co
     JOIN pg_catalog.pg_class cl ON cl.oid = co.conrelid
     JOIN pg_catalog.pg_namespace n ON n.oid = cl.relnamespace
     WHERE n.nspname = 'public'
       AND co.contype IN ('p', 'u', 'f', 'c')
     ORDER BY cl.relname, co.conname`
  )

  const indexRows = await client.query<{ def: string }>(
    `SELECT pg_get_indexdef(i.indexrelid) AS def
     FROM pg_catalog.pg_index i
     JOIN pg_catalog.pg_class t ON t.oid = i.indrelid
     JOIN pg_catalog.pg_namespace n ON n.oid = t.relnamespace
     WHERE n.nspname = 'public'
       AND t.relkind = 'r'
       AND NOT i.indisprimary
       AND NOT EXISTS (
         SELECT 1 FROM pg_catalog.pg_constraint co
         WHERE co.conindid = i.indexrelid AND co.contype IN ('u', 'p')
       )
     ORDER BY pg_get_indexdef(i.indexrelid)`
  )

  return {
    enums: [...enumsMap.entries()].map(([name, labels]) => ({ name, labels })),
    sequences: seqRows.rows.map((s) => ({ name: s.sequencename, lastValue: s.last_value })),
    columns: colRows.rows.map((c) => ({
      table: c.table_name,
      name: c.column_name,
      dataType: c.data_type,
      notNull: c.not_null,
      defaultExpr: c.default_expr,
      identity: c.identity ?? '',
    })),
    constraints: constraintRows.rows.map((c) => ({
      table: c.table_name,
      name: c.conname,
      type: c.contype,
      def: c.def,
    })),
    indexes: indexRows.rows.map((r) => r.def),
  }
}

async function dumpAllPublicTables(): Promise<{
  schema: SchemaDump
  tables: Record<string, Record<string, unknown>[]>
  tableCounts: Record<string, number>
}> {
  const pool = new Pool({ connectionString: DATABASE_URL, max: 1 })
  const client = await pool.connect()
  try {
    const schema = await fetchSchema(client)
    const { rows: tableRows } = await client.query<{ tablename: string }>(
      `SELECT tablename
       FROM pg_catalog.pg_tables
       WHERE schemaname = 'public'
       ORDER BY tablename`
    )

    const tables: Record<string, Record<string, unknown>[]> = {}
    const tableCounts: Record<string, number> = {}
    for (const { tablename } of tableRows) {
      const { rows } = await client.query(`SELECT * FROM ${quoteIdent(tablename)}`)
      tables[tablename] = rows as Record<string, unknown>[]
      tableCounts[tablename] = rows.length
    }

    return { schema, tables, tableCounts }
  } finally {
    client.release()
    await pool.end()
  }
}

export async function listBackups(): Promise<BackupFileInfo[]> {
  const dir = getBackupDir()
  await fs.mkdir(dir, { recursive: true })
  const names = await fs.readdir(dir)
  const infos: BackupFileInfo[] = []
  for (const name of names) {
    if (!isSafeBackupFilename(name)) continue
    const st = await fs.stat(path.join(dir, name))
    if (!st.isFile()) continue
    infos.push({
      filename: name,
      size: st.size,
      createdAt: st.mtime.toISOString(),
    })
  }
  infos.sort((a, b) => b.filename.localeCompare(a.filename))
  return infos
}

export async function pruneOldBackups(): Promise<number> {
  const keep = getBackupKeep()
  const list = await listBackups()
  const extra = list.slice(keep)
  for (const item of extra) {
    await fs.unlink(resolveBackupPath(item.filename))
  }
  return extra.length
}

export async function createBackup(): Promise<BackupCreated> {
  const dir = getBackupDir()
  await fs.mkdir(dir, { recursive: true })

  let filename = makeBackupFilename()
  let filePath = path.join(dir, filename)
  if (await fileExists(filePath)) {
    filename = makeBackupFilename(new Date(Date.now() + 1000))
    filePath = path.join(dir, filename)
  }

  const { schema, tables, tableCounts } = await dumpAllPublicTables()
  const sql = buildSqlDump({
    createdAt: new Date().toISOString(),
    schema,
    tables,
  })
  await fs.writeFile(filePath, sql, 'utf8')
  await pruneOldBackups()

  const st = await fs.stat(filePath)
  return {
    filename,
    size: st.size,
    createdAt: st.mtime.toISOString(),
    tableCounts,
  }
}

export async function readBackupFile(filename: string): Promise<Buffer> {
  const filePath = resolveBackupPath(filename)
  return fs.readFile(filePath)
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath)
    return true
  } catch {
    return false
  }
}
